theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "net"
device = "wlp4s0"
format = "{ssid}: {ip}"
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
format = "{ip}"
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
name = "networkmanager"

[[block]]
block = "disk_space"
path = "/home/kussel"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"

[[block]]
block = "load"
format = "{1m}"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used;M}MB/{mem_total;M}MB({mem_used_percents}%)"
format_swap = "{swap_used;M}MB/{swap_total;M}MB({swap_used_percents}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "custom"
command = "/home/kussel/Scripts/kblayout.sh"
interval = 3
on_click = "xkb-switch -n"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Europe/Berlin"
interval = 60
